# Documentation: https://rmk.rs/docs/configuration.html
[keyboard]
name = "batswing"
product_name = "batswing"
vendor_id = 0x4c4b
product_id = 0x4643
manufacturer = "ruslan"
chip = "nrf52840"
usb_enable = true 

[matrix]
# Row and col pins are mandatory
row_pins = ["P0_11", "P1_04", "P1_06", "P0_10", "P0_09"]
col_pins = ["P0_08", "P0_17", "P0_20", "P0_22", "P0_24", "P1_00", "P0_31", "P0_29", "P0_02", "P1_15", "P1_13", "P1_11"]

# RMK uses col2row as the default matrix diode direction, if you want to use a row2col matrix, add `row2col = true`
# row2col = true

[layout]
rows = 5
cols = 12 
layers = 2
keymap = [
    [
        ["Grave", "Kc1", "Kc2", "Kc3", "Kc4", "Kc5", "Kc6", "Kc7", "Kc8", "Kc9", "Kc0", "Minus"],
        ["Tab", "Q", "W", "E", "R", "T", "Y", "U", "I", "O", "P", "Backspace"],
        ["Escape", "A", "S", "D", "F", "G", "H", "J", "K", "L", "Semicolon", "Quote"],
        ["LShift", "Z", "X", "C", "V", "B", "N", "M", "KpComma", "KpDot", "KpSlash", "RShift"],
        ["_", "LCtrl", "LAlt", "LGui", "Space", "MO(1)", "MO(1)", "Enter", "RGui", "RAlt", "RCtrl", "_"]
    ],
    [
        ["F12", "F1", "F2", "F3", "F4", "F5", "F6", "F7", "F8", "F9", "F10", "F11"],
        ["_", "_", "_", "_", "_", "_", "LeftBracket", "RightBracket", "WM(Kc9, LShift)", "WM(Kc0, LShift)", "KpPlus", "Delete"],
        ["_", "_", "_", "_", "_", "_", "Left", "Down", "Up", "Right", "KpEqual", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "WM(LeftBracket, LShift)", "WM(RightBracket, LShift)", "Minus", "_"],
        ["_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_", "_"]
    ],
]
